### ISSUE TITLE
Crash when trying to use this

### ISSUE THREAD

**Issue by MobileMon** [THALLIVA/any_widget_marquee#1]
I get this crash when trying to use this:

Check failed: scrollChildren == 0 || (scrollChildren > 0 && childrenInHitTestOrder.data()). Semantics update contained scrollChildren but did not have childrenInHitTestOrder

**Comment by MobileMon** [comment]
In order to stop this I wrap the widget in return 
ExcludeSemantics()

Its a bug on the flutter platform talked about here:


https://github.com/flutter/flutter/issues/37886

https://github.com/flutter/flutter/issues/30675

**Comment by Fauzdar1** [comment]
Facing same issue, and I tested my app in the emulators in which it worked fine and when released on play store, it's crashing in multiple phones. Let's see whether this `ExcludeSemantics()` works.

**Comment by Fauzdar1** [comment]
This has fixed the issue, but with the huge irregularity in its speed, I think I should switch.
